# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

set -g mouse on
setw -q -g utf8 on
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -s escape-time 0
# tell term apps (e.g. neovim) know when pane is active/inactive
set -g focus-events on

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g base-index 1

# don't rename windows automatically
set-option -g allow-rename off
set -g renumber-windows on

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# unbind keys
unbind Up
unbind Down
unbind Left
unbind Right

# logging. Have to create .session-logs folder first
# turn off logging session before starting new one.
bind-key P command-prompt -p "Name log file:" \
    "pipe-pane; pipe-pane 'cat >> ~/.session-logs/%%.#I-#P.log"

set -g history-limit 50000

# clipboard when using multi-hop SSH
set -s set-clipboard on
set -g allow-passthrough on

