# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

setw -q -g utf8 on
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -s escape-time 0

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
#set -g status-style 'bg=#333333 fg=#5eacd3'
set -g base-index 1


set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# unbind keys
unbind Up
unbind Down
unbind Left
unbind Right


# logging. Have to create .session-logs folder first
# turn off logging session before starting new one.
bind-key P command-prompt -p "Name log file:" \
    "pipe-pane; pipe-pane 'cat >> ~/.session-logs/%%.#I-#P.log"

# clipboard when using multi-hop SSH
set -s set-clipboard on
set -g allow-passthrough on

# tell term apps (e.g. neovim) know when pane is active/inactive
set -g focus-events on
